# Generated by Django 4.2.4 on 2023-09-21 00:01

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_id', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('gradelvl_id', models.AutoField(primary_key=True, serialize=False)),
                ('gradelvl', models.CharField(max_length=10)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=50)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
                ('gradelvl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
                ('gradelvl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=10)),
                ('birthdate', models.DateField(default=django.utils.timezone.now)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
                ('gradelvl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=50)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
                ('gradelvl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hps_ww_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_qa_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_score_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_percentage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ww_weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_score_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_percentage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('pt_weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qa_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qa_percentage_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('qa_weighted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('initial_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quarterly_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='', max_length=50)),
                ('mname', models.CharField(default='', max_length=50)),
                ('lname', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=25)),
                ('gender', models.CharField(default='', max_length=10)),
                ('address', models.CharField(default='', max_length=255)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
                ('gradelvl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.section')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.teacher')),
            ],
            options={
                'unique_together': {('subject_id', 'dept_id', 'gradelvl_id', 'section_id')},
            },
        ),
    ]
