# Generated by Django 4.2.4 on 2023-09-22 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('quarter_id', models.AutoField(primary_key=True, serialize=False)),
                ('quarter_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='hps_pt_total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='hps_qa_total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='hps_ww_total_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='quarter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.quarter'),
            preserve_default=False,
        ),
    ]
