# Generated by Django 4.2.4 on 2023-09-22 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_studentgrade_gradelevel_studentgrade_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_1',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_10',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_2',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_3',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_4',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_5',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_6',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_7',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_8',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_9',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_pt_total_score',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_qa_10',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_qa_total_score',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_1',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_10',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_2',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_3',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_4',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_5',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_6',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_7',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_8',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_9',
        ),
        migrations.RemoveField(
            model_name='studentgrade',
            name='hps_ww_total_score',
        ),
        migrations.CreateModel(
            name='HpsScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hps_ww_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_ww_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_4', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_5', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_6', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_7', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_8', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_9', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_pt_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_qa_10', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hps_qa_total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('gradelevel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.quarter')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
            ],
        ),
    ]
