# Generated by Django 4.2.4 on 2023-09-24 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_studentgrade_hps_pt_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hpsscores',
            name='hps_qa_10',
        ),
    ]
