# Generated by Django 4.2.4 on 2023-10-01 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_admin_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50)),
                ('task_score', models.CharField(max_length=50)),
                ('task_status', models.CharField(max_length=50)),
                ('dept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.department')),
                ('gradelvl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
                ('quarter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.quarter')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.section')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
            ],
        ),
    ]
