# Generated by Django 4.2.4 on 2023-10-02 14:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_weeklyprogress_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogress',
            name='input_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
