# Generated by Django 4.2.4 on 2023-10-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_alter_weeklyprogress_input_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyprogress',
            name='input_date',
            field=models.DateField(),
        ),
    ]
