# Generated by Django 4.2.4 on 2023-10-04 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_alter_weeklyprogress_input_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_present', models.BooleanField(default=True)),
                ('grade_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
            ],
            options={
                'unique_together': {('student', 'date', 'grade_level', 'section', 'subject')},
            },
        ),
    ]
