# Generated by Django 4.2.4 on 2023-10-06 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_responses', models.IntegerField(default=0)),
                ('percentage_correct', models.FloatField(default=0.0)),
                ('gradelvl_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.gradelevel')),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.section')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.subject')),
            ],
        ),
    ]
