# Generated by Django 4.2.4 on 2023-10-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_itemanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemanalysis',
            name='item_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
