# Generated by Django 4.2.4 on 2023-10-06 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_itemanalysis_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemanalysis',
            name='quarter_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='database.quarter'),
            preserve_default=False,
        ),
    ]
