# Generated by Django 4.2.4 on 2023-10-22 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0020_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
