# Generated by Django 4.2.4 on 2023-10-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0021_studentgrade_date_input_ww_score_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_3',
            field=models.DateField(blank=True, null=True),
        ),
    ]
