# Generated by Django 4.2.4 on 2023-10-23 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0022_studentgrade_date_input_ww_score_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_pt_score_9',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_qa_score',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_10',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_5',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_6',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_7',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_8',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='date_input_ww_score_9',
            field=models.DateField(blank=True, null=True),
        ),
    ]
