# Generated by Django 4.2.4 on 2023-10-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0023_studentgrade_date_input_pt_score_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='ww_score_1_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
