# Generated by Django 4.2.4 on 2023-10-23 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0024_studentgrade_ww_score_1_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='ww_score_2_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
