# Generated by Django 4.2.4 on 2023-10-29 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0028_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
