from django.urls import path
from .views import *
from . import views
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView



urlpatterns = [
    path('login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('add-student/', AddStudentView.as_view(), name='add_student'),
    path('edit-student/<int:student_id>/',EditStudentView.as_view(), name='edit-student'),
    path('del-student/<int:student_id>/', views.delete_student, name='delete-student'),
    path('user-data/', UserDataView.as_view(), name='user-data'),
    path('admin-login/', AdminTokenObtainPairView.as_view(), name='admin-login'),
    path('add-admin/', AdminRegistrationView.as_view(), name='add-admin'), 
    path('add-teacher/', AddTeacherView.as_view(), name='add-teacher'), 
    path('filter-teachers/<int:grade_level_id>/', views.filter_teachers, name='filter_teachers'),
    path('filter-hs-teachers/<int:grade_level_id>/', views.filter_hs_teachers, name='filter_hs_teachers'),
    path('filter-shs-teachers/<int:grade_level_id>/', views.filter_shs_teachers, name='filter_shs_teachers'),
    path('edit-teacher/<int:teacher_id>/',EditTeacherView.as_view(), name='edit-teacher'),
    path('del-teacher/<int:teacher_id>/', views.delete_teacher, name='delete-teacher'),
    path('departments/', views.get_departments, name='get-departments'),
    path('gradelevels/',views.get_gradelvl_elem, name='get-gradelevels'),
    path('filter-sections/<int:grade_level_id>/', views.filter_sections, name='filter_sections'),
    path('add-elemsection/', addElemSections.as_view(), name="add-elemsection"),
    path('edit-sections/<int:section_id>/', EditSectionView.as_view(), name='edit-section'),  
    path('del-sections/<int:section_id>/', views.delete_section, name='delete_section'),
    path('filter-hs-sections/<int:grade_level_id>/',views.filter_hs_sections, name='filter-hs-sections'),
    path('hs-gradelevels/', views.get_gradelvl_hs, name='get-hs-gradelevels'),
    path('add-hssection/', addHsSections.as_view(), name='add-hssections'),
    path('filter-shs-sections/<int:grade_level_id>/',views.filter_shs_sections, name='filter-hs-sections'),
    path('shs-gradelevels/', views.get_gradelvl_shs, name='get-hs-gradelevels'),
    path('add-shssection/', addsHsSections.as_view(), name='add-hssections'),
    path('filter-elem-courses/<int:grade_level_id>/', views.filter_elem_courses, name='filter-elem-courses'),
    path('edit-subjects/<int:subject_id>/', EditSubjectView.as_view(), name='edit-subject'),
    path('del-subjects/<int:subject_id>/', views.delete_subject, name='delete-subject'),
    path('add-elem-subject/', addElemSubjects.as_view(), name='add-elem-subject'),
    path('filter-hs-courses/<int:grade_level_id>/', views.filter_hs_courses, name='filter-hs-courses'),
    path('add-hs-subject/', addHsSubjects.as_view(), name='add-hs-subject'),
    path('filter-shs-courses/<int:grade_level_id>/', views.filter_shs_courses, name='filter-shs-courses'),
    path('add-shs-subject/', addsHsSubjects.as_view(), name='add-shs-subject'),
    path('get-gradelvldept/<int:department_id>/', views.get_grade_levels_by_department, name='get-gradelevels-by-department'),
    path('get-sectiondept/<int:department_id>/<int:grade_level_id>/', views.get_sections_by_department, name='get-sections-by-department'),
    path('filter-students/<int:dept_id>/<int:grade_level_id>/<int:section_id>/', views.filter_students, name='filter_teachers'),
    path('assignments/', views.AssignmentListCreateView.as_view(), name='assignment-list-create'),
    path('assignments/<int:teacher_id>/', views.AssignmentListCreateView.as_view(), name='assignment-list-create'),
    path('del-assignments/<int:pk>/', views.AssignmentRetrieveUpdateDestroyView.as_view(), name='assignment-detail'),
    path('get-subjects/<int:dept_id>/<int:gradelvl_id>/', views.get_subjects_by_dept_and_grade_level, name='et_subjects_by_dept_and_grade_level'),
    path('get-deptbyid/<int:dept_id>/', views.getDeptById, name='getdeptbyid'),
    path('get-grlvlbyid/<int:gradelvl_id>/', views.getGradelvlById, name='getgrlvlbyid'),   
    path('get-sectionbyid/<int:section_id>/', views.getSectionById, name='getsectbyid'),
    path('get-subjbyid/<int:subject_id>/', views.getSubjectById, name='getsubjbyid'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('teacher-profile/', views.teacher_profile, name='user-profile'),
    path('admin-profile/', views.admin_profile, name='admin-profile'),
    path('calculate_weighted_scores/<int:student_id>/', views.calculate_weighted_scores_view, name='calculate_weighted_scores'),
    path('student-profile/', views.student_profile, name='student-profile'),
    path('student-grade/', views.StudentGradeListCreateView.as_view(), name='studentgrade-list-create'),
    path('student-grade/update/<int:student_id>/<int:subject_id>/<int:gradelevel_id>/<int:section_id>/<int:quarter_id>/', views.StudentGradeUpdateView.as_view(), name='studentgrade-update'),
    path('student-grade/batch-update/', StudentGradeBatchUpdateView.as_view(), name='studentgrade-batch-update'),
    path('student-grade/filter/', views.StudentGradesFilterView.as_view(), name='studentgrade-filter'),
    path('all-subj-student-grade/filter/', views.AllSubjStudentGradesFilterView.as_view(), name='allsubjstudentgrade-filter'),
    path('quarters/', QuarterListCreateView.as_view(), name='quarter-list'),
    path('hps/', HPSListCreateView.as_view(), name='hps-list'),
    path('hps/filter/', views.HPSFilterView.as_view(), name='HPS-filter'),
    path('hps/<int:pk>/', views.HPSUpdateView.as_view(), name='HPS-update'),
    path('student-grades/by-quarter/<int:quarter_id>/', StudentGradeByQuarterListView.as_view(), name='studentgrade-by-quarter'),
    path('hps/by-quarter/<int:quarter_id>/', HPSByQuarterListView.as_view(), name='hps-by-quarter'),
    path('admin/profile/', AdminProfileView.as_view(), name='admin-profile'),
    path('get-subjgrades/<int:grade_level_id>/<int:section_id>/<int:subject_id>/<int:quarter_id>/',views.GradesByParams.as_view(),name='grades-by-params'),
    path('student-count/', StudentCountView.as_view(), name='student_count'),
    path('teacher-count/', TeacherCountView.as_view(), name='student_count'),
    path('add-weeklyprogress/', WeeklyProgressListCreateView.as_view(), name='add-weekly-progress'),
    path('get-weeklyprog/<int:grade_level_id>/<int:section_id>/<int:subject_id>/<int:quarter_id>/',views.getWeeklyProgress.as_view(),name='grades-by-params'),
    path('weekly-prog/batch-update/', WeeklyProgressBatchUpdateView.as_view(), name='studentgrade-batch-update'),
    path('remove-task/<int:pk>/', views.RemoveTaskView.as_view(), name='remove-task'),
    path('filter-weekly-progress/', views.filter_weekly_progress, name='filter_weekly_progress'),
    path('fetch-grades/<int:student_id>/<int:subject_id>/<int:quarter_id>/',views.StudentGradesListView.as_view(),name='grades-by-params'),
    path('add-itemanalysis/', ItemAnalysisListCreateView.as_view(), name='item-analysis-add'),
    path('item-analysis/<int:gradelvl_id>/<int:section_id>/<int:subject_id>/<int:quarter_id>/', views.ItemAnalysisWithItemNumberView.as_view(), name='item-analysis-with-item-number'),
    path('item-analysis/batch-update/', ItemAnalysisBatchUpdateView.as_view(), name='itemanalysis-batch-update'),
    path('indiv-student-grade/filter/', views.GetStudentGrade.as_view(), name='indiv-studentgrade-filter'),
    path('add-announcement/', AnnouncementCreateView.as_view(), name='add-announcement'),
    path('announcements/<int:pk>/', views.AnnouncementEditDeleteView.as_view(), name='announcement-detail'),
    path('change-password/', ChangePasswordView.as_view(), name='change-password'),
    path('teacher/profile/', TeacherProfileView.as_view(), name='teacher-profile'),
    path('student/profile/', StudentProfileView.as_view(), name='student-profile'),
    path('get-announcements/<int:department_id>/', AnnouncementByDepartmentView.as_view(), name='announcements-by-department'),
    path('password-reset/', PasswordResetVieww.as_view(), name='password-reset'),
    path('password-reset-confirm/', PasswordResetConfirmVieww.as_view(), name='password-reset-confirm'),
    path('student-average/', views.StudentAverageListCreateView.as_view(), name='studentaverage-list-create'),
    path('average/<int:pk>/', views.AverageUpdateView.as_view(), name='average-update'),
    path('average/filter/', views.AverageFilterView.as_view(), name='average-filter'),
    path('all-average/filter/', views.AllAverageFilterView.as_view(), name='all-average-filter'),
    path('add-queries/', QueriesListCreateView.as_view(), name='queries-add'),
    path('queries/<int:pk>/', views.QueriesRetrieveUpdateDestroyView.as_view(), name='queries-detail'),

]
